DROP DATABASE IF EXISTS `q_and_a`;

CREATE DATABASE `q_and_a`;

\c q_and_a;

-- psql -U postgres < server/db/schema.sql

-- ---
-- Table 'questions'
--
-- ---
DROP TABLE IF EXISTS `questions`;

CREATE TABLE `questions` (
  `id` int GENERATED BY DEFAULT AS IDENTITY,
  `body` varchar(1000) NOT NULL,
  `asker_name` varchar(60) NOT NULL
  `date` timestamp with time zone  NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `helpfulness` int NOT NULL DEFAULT 0,
  `reported` boolean NULL DEFAULT false,
  `user_id` int NOT NULL
);

-- ---
-- Table 'answers'
--
-- ---

DROP TABLE IF EXISTS `answers`;

CREATE TABLE `answers` (
  `id` int GENERATED BY DEFAULT AS IDENTITY,
  `question_id` int NOT NULL,
  `body` varchar(1000) NOT NULL,
  `answerer_name` varchar(60) NOT NULL
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `helpfulness` int NOT NULL DEFAULT 0,
  `reported` boolean NOT NULL DEFAULT false,
  `user_id` int NOT NULL
);

-- ---
-- Table 'photos'
--
-- ---

DROP TABLE IF EXISTS `photos`;

CREATE TABLE `photos` (
  `id` int GENERATED BY DEFAULT AS IDENTITY,
  `url` text NOT NULL,
  `answer_id` int NOT NULL,
);

-- ---
-- Table 'users'
--
-- ---

DROP TABLE IF EXISTS `users`;

CREATE TABLE `users` (
  `id` int GENERATED BY DEFAULT AS IDENTITY,
  `email` varchar(60) NOT NULL UNIQUE,
);

-- ---
-- Foreign Keys
-- ---

ALTER TABLE `answers` ADD FOREIGN KEY (question_id) REFERENCES `questions` (question_id) ON DELETE CASCADE;
ALTER TABLE `photos` ADD FOREIGN KEY (answer_id) REFERENCES `answers` (answer_id) ON DELETE CASCADE;